### ISSUE TITLE
Alerts behind other hud elements

### ISSUE THREAD

**Issue by inferno771** [thelindat/linden_outlawalert#11]
Not sure if this is an issue with the outlaw alert or with other elements of our hud, but the alerts are showing behind other things. I've attached a picture of an example.

![preview](https://user-images.githubusercontent.com/531463/127319474-34bb9efc-a178-4744-bbc1-bda26b526493.png)

**Comment by Kraleemil** [comment]
> Not sure if this is an issue with the outlaw alert or with other elements of our hud, but the alerts are showing behind other things. I've attached a picture of an example.
> 
> ![preview](https://user-images.githubusercontent.com/531463/127319474-34bb9efc-a178-4744-bbc1-bda26b526493.png)

Just start the alert system after the HUD or before

**Comment by Kraleemil** [comment]
And you can join his discord and get support there

**Comment by inferno771** [comment]
Thanks, loading it after the hud worked!
