### ISSUE TITLE
no Fines in the SQL

### ISSUE THREAD

**Issue by Rowon420** [thelindat/linden_outlawalert#13]
script:mdt] SCRIPT ERROR: @mdt/sv_mdt.lua:34: attempt to get length of a nil value (local 'fines')
[          script:mdt] > ref (@mdt/sv_mdt.lua:34)

**Comment by CollapsedLegacy** [comment]
This isn't regarding linden_outlawalert, you need to contact the mdt people.

**Comment by thelindat** [comment]
Fines are from esx_billing
