### ISSUE TITLE
Location Alert

### ISSUE THREAD

**Issue by Gmzy-1** [thelindat/linden_outlawalert#4]
Hi,

I'm having an issue with the blips being displayed in the wrong location from the one where the crime was committed.

For example, below the crime was around Maze Bank area and it's going towards the top of the flats in the city
![image](https://user-images.githubusercontent.com/79610647/109078366-1c5f3a00-76f5-11eb-8ea9-7511226263d1.png)

Any ideas?

**Comment by thelindat** [comment]
Should be resolved in latest commit, let me know

**Comment by Gmzy-1** [comment]
Hi,

Still seems to be displaying it in the same area for each alert
![image](https://user-images.githubusercontent.com/79610647/109162013-a0560800-776f-11eb-9942-29541f204911.png)

**Comment by Gmzy-1** [comment]
It seems to only do it when you're not right next to the crime.

**Comment by thelindat** [comment]
Onesync or infinity?

**Comment by Gmzy-1** [comment]
OneSync with Infinity.

**Comment by thelindat** [comment]
Alright so I have it set to put the blip on the entity for a while then drop off, which won't work for infinity.
Try the latest commit and let me know if it works.

**Comment by Gmzy-1** [comment]
Still no luck unfortunately

**Comment by thelindat** [comment]
What's the result from
`print( ('netid: %s  entity: %s  coords: %s'):format(data.netId, NetworkGetEntityFromNetworkId(data.netId), data.coords) )` added into createBlip

**Comment by Gmzy-1** [comment]
Seems to be working perfectly now, thanks!
